### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by kenany** [Saucesum/SauceBot#1]
I noticed that the dependencies are installed used a shell script, but with npm there's actually a better way to manage dependencies. With a `package.json` file, you can specify your dependencies and a version range and npm will install them all with one command:

``` bash
$ npm install
```

However, I didn't want to open a pull request to add the file because I see that you have `*.json` in your `.gitignore`. I don't know enough about the repository (yet?) to understand which JSON files you're ignoring, so I decided to bring this up first before I fork.

You can check out the `package.json` [spec](https://npmjs.org/doc/json.html) if you'd like. I'd be happy to help you write one.

**Comment by ghost** [comment]
Cheers! There's now a package.json file describing the project and dependencies.
This project hasn't had much activity from anyone but me, so I hadn't really gotten around to setting it up properly.

The *.json in .gitignore is for the server configuration file. I have now made that explicit.
