### ISSUE TITLE
Got Server Running....

### ISSUE THREAD

**Issue by hawkmyg** [Saucesum/SauceBot#5]
How do I get bot into my channel via linux command?
I run node subot/server/server.js config
and it loads and runs the server but bot doesnt connect to channels please Help.

{
    "Server": {
        "Name": "xsuxbot",
        "Port": 6667
    },
    "MySQL": {
        "Username": "%%%",
        "Password": "%%%",
        "Database": "%%%"
    },
    "Logging": {
        "Root": "/root/Sauce/SauceBot/bin/server/../../logs/"
    },
    "Graphing": {
        "Host": "Server IP",
        "Port": 8125,
        "Name": "saucebot"
    },
    "API": {
        "Twitch": "xsuxbot",
        "TwitchToken": "oauth:key",
        "LastFM": "",
        "Steam": ""
    }
}

**Comment by ghost** [comment]
The server itself doesn't connect to any chat services. You'll need to have a client running as well if you want it to join channels. The reason behind this is to make it possible to use the bot with multiple chat protocols, and not just Twitch.tv IRC.

Unfortunately, I don't think the old SauceBot Twitch client works anymore, as Twitch has changed the way chat authentication is done. Fixing it up shouldn't be too hard, however. If you don't know how, I would probably suggest trying to find a different bot. It was on my TODO list to make it easier to use/run, but I never got that far.

**Comment by hawkmyg** [comment]
:( well if you ever get a chance please let me know if you know of any bots that do work with twitch that I can use like sauce.
